# Generated by Django 3.0.5 on 2020-04-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='no model name', max_length=100)),
                ('trim', models.TextField(max_length=200, null=True)),
                ('description', models.TextField(default='no model description')),
                ('image_file', models.ImageField(null=True, upload_to='images/')),
                ('image_url', models.TextField(max_length=200, null=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='mycars.Year')),
            ],
        ),
    ]
