# Generated by Django 3.0.5 on 2020-04-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltype',
            name='make',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
