# Generated by Django 3.0.5 on 2020-04-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycars', '0002_modeltype_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modeltype',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
